In [1]:
%pip install -r requirements.txt

Collecting pandas>3.0 (from -r requirements.txt (line 1))
  Using cached pandas-3.0.2-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting CFEDemands>=0.8.2 (from -r requirements.txt (line 2))
  Using cached cfedemands-0.8.2-py3-none-any.whl.metadata (2.3 kB)
Collecting ligonlibrary>=0.2 (from -r requirements.txt (line 3))
  Using cached ligonlibrary-0.2.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: ipympl in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.9.8)
Requirement already satisfied: numpy>=1.26.0 in /srv/conda/lib/python3.11/site-packages (from pandas>3.0->-r requirements.txt (line 1)) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/lib/python3.11/site-packages (from pandas>3.0->-r requirements.txt (line 1)) (2.9.0.post0)
Collecting ConsumerDemands>=0.3.dev0 (from CFEDemands>=0.8.2->-r requirements.txt (line 2))
  Using cached consumerdemands-0.5.0-py3-none-any.whl.metadata (1.9 kB)
Collecting fsspec (from CFEDemands>=0.8.2->-r requirements.txt (line 2))
  Using cached fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: importlib-metadata>=6.7.0 in /srv/conda/lib/python3.11/site-packages (from CFEDemands>=0.8.2->-r requirements.txt (line 2)) (8.7.0)
Requirement already satisfied: matplotlib>=3.5.1 in /srv/conda/lib/python3.11/site-packages (from CFEDemands>=0.8.2->-r requirements.txt (line 2)) (3.10.8)
Requirement already satisfied: scikit-learn in /srv/conda/lib/python3.11/site-packages (from CFEDemands>=0.8.2->-r requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: scipy>=1.7.3 in /srv/conda/lib/python3.11/site-packages (from CFEDemands>=0.8.2->-r requirements.txt (line 2)) (1.17.1)
Requirement already satisfied: google-api-python-client>=2.178.0 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary>=0.2->-r requirements.txt (line 3)) (2.190.0)
Requirement already satisfied: google-auth-oauthlib>=1.2.2 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary>=0.2->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: gspread>=5.12.0 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary>=0.2->-r requirements.txt (line 3)) (5.12.4)
Collecting gspread-pandas>=3.3.0 (from ligonlibrary>=0.2->-r requirements.txt (line 3))
  Using cached gspread_pandas-3.3.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: openpyxl>=3.1.5 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary>=0.2->-r requirements.txt (line 3)) (3.1.5)
Requirement already satisfied: python-gnupg>=0.5.2 in /srv/conda/lib/python3.11/site-packages (from ligonlibrary>=0.2->-r requirements.txt (line 3)) (0.5.6)
Collecting python-magic>=0.4.27 (from ligonlibrary>=0.2->-r requirements.txt (line 3))
  Using cached python_magic-0.4.27-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting thefuzz>=0.22.1 (from ligonlibrary>=0.2->-r requirements.txt (line 3))
  Using cached thefuzz-0.22.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: ipython<10 in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 4)) (9.10.0)
Requirement already satisfied: ipywidgets<9,>=7.6.0 in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 4)) (8.1.5)
Requirement already satisfied: pillow in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 4)) (11.1.0)
Requirement already satisfied: traitlets<6 in /srv/conda/lib/python3.11/site-packages (from ipympl->-r requirements.txt (line 4)) (5.14.3)
Requirement already satisfied: decorator>=4.3.2 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (5.1.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /srv/conda/lib/python3.11/site-packages (from ipython<10->ipympl->-r requirements.txt (line 4)) (4.12.2)
Requirement already satisfied: comm>=0.1.3 in /srv/conda/lib/python3.11/site-packages (from ipywidgets<9,>=7.6.0->ipympl->-r requirements.txt (line 4)) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in /srv/conda/lib/python3.11/site-packages (from ipywidgets<9,>=7.6.0->ipympl->-r requirements.txt (line 4)) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.12 in /srv/conda/lib/python3.11/site-packages (from ipywidgets<9,>=7.6.0->ipympl->-r requirements.txt (line 4)) (3.0.16)
Requirement already satisfied: contourpy>=1.0.1 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (24.2)
Requirement already satisfied: pyparsing>=3 in /srv/conda/lib/python3.11/site-packages (from matplotlib>=3.5.1->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: wcwidth in /srv/conda/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython<10->ipympl->-r requirements.txt (line 4)) (0.6.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (0.22.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (2.41.1)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (0.3.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (2.30.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /srv/conda/lib/python3.11/site-packages (from google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (4.2.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /srv/conda/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (2.32.3)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /srv/conda/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (6.2.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /srv/conda/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /srv/conda/lib/python3.11/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (4.9.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (2026.2.25)
Requirement already satisfied: pyasn1>=0.1.3 in /srv/conda/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client>=2.178.0->ligonlibrary>=0.2->-r requirements.txt (line 3)) (0.6.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /srv/conda/lib/python3.11/site-packages (from google-auth-oauthlib>=1.2.2->ligonlibrary>=0.2->-r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: zipp>=3.20 in /srv/conda/lib/python3.11/site-packages (from importlib-metadata>=6.7.0->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (3.23.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /srv/conda/lib/python3.11/site-packages (from jedi>=0.18.1->ipython<10->ipympl->-r requirements.txt (line 4)) (0.8.6)
Requirement already satisfied: et_xmlfile in /srv/conda/lib/python3.11/site-packages (from openpyxl>=3.1.5->ligonlibrary>=0.2->-r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: ptyprocess>=0.5 in /srv/conda/lib/python3.11/site-packages (from pexpect>4.3->ipython<10->ipympl->-r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: six>=1.5 in /srv/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>3.0->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: oauthlib>=3.0.0 in /srv/conda/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=1.2.2->ligonlibrary>=0.2->-r requirements.txt (line 3)) (3.3.1)
Requirement already satisfied: executing>=1.2.0 in /srv/conda/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython<10->ipympl->-r requirements.txt (line 4)) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /srv/conda/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython<10->ipympl->-r requirements.txt (line 4)) (3.0.1)
Requirement already satisfied: pure_eval in /srv/conda/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython<10->ipympl->-r requirements.txt (line 4)) (0.2.3)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from thefuzz>=0.22.1->ligonlibrary>=0.2->-r requirements.txt (line 3))
  Using cached rapidfuzz-3.14.5-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: joblib>=1.2.0 in /srv/conda/lib/python3.11/site-packages (from scikit-learn->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /srv/conda/lib/python3.11/site-packages (from scikit-learn->CFEDemands>=0.8.2->-r requirements.txt (line 2)) (3.6.0)
Using cached pandas-3.0.2-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.3 MB)
Using cached cfedemands-0.8.2-py3-none-any.whl (98 kB)
Using cached ligonlibrary-0.2.0-py3-none-any.whl (19 kB)
Using cached consumerdemands-0.5.0-py3-none-any.whl (14 kB)
Using cached gspread_pandas-3.3.0-py2.py3-none-any.whl (27 kB)
Using cached python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Using cached thefuzz-0.22.1-py3-none-any.whl (8.2 kB)
Using cached rapidfuzz-3.14.5-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
Using cached fsspec-2026.3.0-py3-none-any.whl (202 kB)
Installing collected packages: rapidfuzz, python-magic, fsspec, thefuzz, pandas, ConsumerDemands, CFEDemands, gspread-pandas, ligonlibrary
  Attempting uninstall: pandas━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/9 [fsspec]
    Found existing installation: pandas 2.2.3━━━━━━━━━━━━━━━━━ 2/9 [fsspec]
    Uninstalling pandas-2.2.3:[91m╸━━━━━━━━━━━━━━━━━━━━━━ 4/9 [pandas]
      Successfully uninstalled pandas-2.2.3m━━━━━━━━━━━━━━━━━━━━━━ 4/9 [pandas]
  Attempting uninstall: gspread-pandasm╺━━━━━━━━━━━━━━━━━ 5/9 [ConsumerDemands]
    Found existing installation: gspread-pandas 2.2.3━━━━━━━━━ 5/9 [ConsumerDemands]
    Uninstalling gspread-pandas-2.2.3:0m━━━━━━━━━━━━━━━━━ 5/9 [ConsumerDemands]
      Successfully uninstalled gspread-pandas-2.2.3━━━━━━━━━━━ 5/9 [ConsumerDemands]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [ligonlibrary][ConsumerDemands]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
linearmodels 0.0.0 requires Cython>=3.0.10, which is not installed.
linearmodels 0.0.0 requires setuptools_scm[toml]<9.0.0,>=8.0.0, which is not installed.
ibis-framework 9.2.0 requires pandas<3,>=1.5.3, but you have pandas 3.0.2 which is incompatible.
otter-grader 6.1.3 requires wrapt<2.0.0,>=1.16.0, but you have wrapt 2.1.1 which is incompatible.
Successfully installed CFEDemands-0.8.2 ConsumerDemands-0.5.0 fsspec-2026.3.0 gspread-pandas-3.3.0 ligonlibrary-0.2.0 pandas-3.0.2 python-magic-0.4.27 rapidfuzz-3.14.5 thefuzz-0.22.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from ligonlibrary.sheets import read_sheets
import unicodedata as unicodedata
import re
import difflib

# import library for panama csv 
#panama food expenditures with household distributions ; the main df
panama_household_dist_df = "1QKSfYFQu8xR4I-vHfPK00mO-1XjqrQgVpCGGpDrustI" 
x = read_sheets(panama_household_dist_df,sheet='Food Expenditures (2003)')

x.head()

          i     t        m               j  Expenditure
0  20031000  2003  Herrera  Aceite Vegetal          2.8
1  20031000  2003  Herrera       Ahí Verde          1.2
2  20031000  2003  Herrera             Ajo          1.0
3  20031000  2003  Herrera            Apio          0.3
4  20031000  2003  Herrera           Arroz         10.5

In [3]:
panama_foods_nutrients_df = "1C3XN4V08r4JAfLstg94EgOrrlBqw4E48w2SYjK8qxnY" 
y = read_sheets(panama_foods_nutrients_df,sheet='central_american_fct - FCT', nheaders=3)
y.head()

,Nutrient,Agua\n%,Energía,Proteina,Grasa Total,Carbo-\nhidratos,Fibra Diet. \ntotal,Ceniza,Calcio,Fosforo,...,Colesterol,Potasio,Sodio,Zinc,Magnesio,Vit. B6,Vit. B12,Ac. Fólico,Folato \nEquiv. FD,Fracción \nComestible
,Unit,,Kcal.,g,g,g,g,g,mg,mg,...,mg,mg,mg,mg,mg,mg,mcg,mcg,mcg,%
,Name,,,,,,,,,,...,,,,,,,,,,
Code,,,,,,,,,,,,,,,,,,,,,
,01. PRODUCTOS LACTEOS Y SIMILARES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,"CREMA, ESPESA",57.71,345.0,2.05,37.00,2.79,0.0,0.45,65.0,62.0,...,137.0,75.0,38.0,0.23,7.0,0.03,0.18,0.0,4.0,1.0
1002,"CREMA, RALA",73.75,195.0,2.70,19.31,3.66,0.0,0.58,96.0,80.0,...,66.0,122.0,40.0,0.27,9.0,0.03,0.22,0.0,2.0,1.0
1003,"CREMA, SUSTITUTO NO LÁCTEO, EN POLVO",2.21,546.0,4.79,35.48,54.88,0.0,2.64,22.0,422.0,...,0.0,812.0,181.0,0.51,4.0,0.00,0.00,0.0,0.0,1.0
1004,"LECHE DE BURRA, FLUIDA",90.20,43.0,1.70,1.20,6.50,NaN,0.40,126.0,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [4]:
?read_sheets

Signature:
read_sheets(
    key: 'str | Mapping[str, str]',
    json_creds: 'Optional[str]' = None,
    sheet: 'Optional[str | int]' = None,
    force_numeric: 'bool' = True,
    nheaders: 'int' = 1,
)
Docstring:
Read a Google Sheet via key or URL, optionally using service-account credentials.

Parameters mirror the historical interface used in course material.
File:      /srv/conda/lib/python3.11/site-packages/ligonlibrary/sheets.py
Type:      function

In [4]:
grouped_x = x.groupby('i')['j'].apply(list).reset_index()
grouped_x.head()

         i                                                  j
0  2003199  [Aceite Vegetal, Ahí Verde, Apio, Arroz, Azúca...
1  2003201  [Arroz, Azúcar, Café Y Té, Carne De Res, Galle...
2  2003202  [Arroz, Azúcar, Café Y Té, Cebolla, Galletas /...
3  2003203  [Aceite Vegetal, Ajo, Arroz, Azúcar, Café Y Té...
4  2003204  [Aceite Vegetal, Ajo, Arroz, Azúcar, Café Y Té...

In [5]:
# function for cleaning ONE food name
def clean_one_food(s):
    if pd.isna(s):
        return None
    s = str(s).upper().strip()
    # remove accents
    s = ''.join(
        c for c in unicodedata.normalize('NFKD', s)
        if not unicodedata.combining(c)
    )
# replacing separators with spaces
    s = s.replace('/', ' ')
    s = s.replace('-', ' ')
    s = s.replace(',', ' ')
    s = s.replace('.', ' ')
# removing parentheses/brackets
    s = re.sub(r'[\(\)\[\]\{\}]', ' ', s)
# keeping only letters, numbers, spaces
    s = re.sub(r'[^A-Z0-9\s]', ' ', s)
# normalizing common filler words
    replacements = {
        'DE LA ': ' ',
        'DE LAS ': ' ',
        'DE LOS ': ' ',
        'DE EL ': ' ',
        ' DEL ': ' ',
        ' DE ': ' ',
        ' Y ': ' '
    }
    s = f' {s} '
    for old, new in replacements.items():
        s = s.replace(old, f' {new} ')
    s = s.strip()
# collapsing multiple spaces
    s = re.sub(r'\s+', ' ', s).strip()
    return s


# function for cleaning the LIST of foods
def clean_food_list(food_list):
    if not isinstance(food_list, list):
        return None
    return [clean_one_food(food) for food in food_list if pd.notna(food)]


# apply to grouped table
grouped_x['j_clean'] = grouped_x['j'].apply(clean_food_list)

grouped_x.head()

,i,j,j_clean
0,2003199,"[Aceite Vegetal, Ahí Verde, Apio, Arroz, Azúca...","[ACEITE VEGETAL, AHI VERDE, APIO, ARROZ, AZUCA..."
1,2003201,"[Arroz, Azúcar, Café Y Té, Carne De Res, Galle...","[ARROZ, AZUCAR, CAFE TE, CARNE RES, GALLETAS P..."
2,2003202,"[Arroz, Azúcar, Café Y Té, Cebolla, Galletas /...","[ARROZ, AZUCAR, CAFE TE, CEBOLLA, GALLETAS PAS..."
3,2003203,"[Aceite Vegetal, Ajo, Arroz, Azúcar, Café Y Té...","[ACEITE VEGETAL, AJO, ARROZ, AZUCAR, CAFE TE, ..."
4,2003204,"[Aceite Vegetal, Ajo, Arroz, Azúcar, Café Y Té...","[ACEITE VEGETAL, AJO, ARROZ, AZUCAR, CAFE TE, ..."

In [6]:
y.iloc[:, 0]

Code
            01.  PRODUCTOS LACTEOS Y SIMILARES
1001                             CREMA, ESPESA
1002                               CREMA, RALA
1003     CREMA, SUSTITUTO NO LÁCTEO,  EN POLVO
1004                    LECHE DE BURRA, FLUIDA
                         ...
22021                              SAL DE MESA
22022         SAZONADOR MOLIDO NO ESPECIFICADO
22023                    SAZONADOR, PARA POLLO
22024                            TOMILLO, SECO
22025                       VAINILLA, EXTRACTO
Name: (Nutrient, Unit, Name), Length: 1466, dtype: str

In [ ]:
foods_long = grouped_x[['i', 'j_clean']].explode('j_clean').rename(columns={'i': 'household_id', 'j_clean': 'searched_food'})
y_names = y.iloc[:, 0].astype(str)

results = []

for food in foods_long['searched_food'].dropna().unique():
    mask = y_names.str.contains(food, regex=False, na=False)
    matched_y = y[mask].copy()
    
    if not matched_y.empty:
        temp_foods = foods_long[foods_long['searched_food'] == food]
        for _, food_row in temp_foods.iterrows():
            temp = matched_y.copy()
            temp['household_id'] = food_row['household_id']
            temp['searched_food'] = food
            results.append(temp)

final_df = pd.concat(results, ignore_index=True) if results else pd.DataFrame()
final_df.head()